/*
@author Kevin Chappell
@version 1.0
@date December 16, 2016
@description Error when tables are missing a schema name designation
*/
package com.datical.hammer.core.sqlrules

import com.datical.db.project.Project;
import com.datical.hammer.core.rules.Response;
import com.datical.hammer.core.rules.Response.ResponseType;
import com.datical.hammer.core.rules.WithComments;
import com.datical.hammer.core.rules.WithoutComments;


function boolean hasSelectStar(String mySql)
{
	System.out.println("Validation called For : "+ mySql);
		Pattern pattern1 = Pattern.compile("\\s+");
		Matcher matcher1 = pattern1.matcher(mySql) ;
	    Pattern pSelectStar = Pattern.compile("select * from ",Pattern.CASE_INSENSITIVE);
		Matcher mSelectStar = pSelectStar.matcher( matcher1.replaceAll(" "));
	    return mSelectStar.matches();
}

	
rule " Code with Select * in it "
    salience 1
    when
        wc : WithoutComments(hasSelectStar(getText())) 
		
    then
 		String errorMessage =  "\n File " + wc.getSqlFile().getName() + " Contains Select * Statement ";
        insert(new Response(ResponseType.FAIL, errorMessage, drools.getRule().getName()));
end
