package com.datical.hammer.core.forecast


import com.datical.hammer.core.rules.GeneratedSQL;
import com.datical.hammer.core.rules.Response;
import com.datical.hammer.core.rules.Response.ResponseType;
import org.apache.commons.lang.StringUtils;
import java.util.List;
import java.util.ArrayList;


def StripOracleComments(String[] mYText) {
    boolean inBlock = false;
	List<String> filteredText = new ArrayList();
	StringBuilder newline = new StringBuilder();
	for (String line: mYText) {
		i = 0;
		char[] chars = line.toCharArray();
		if (!inBlock) newline = new StringBuilder();
		while (i < line.length()) {
                if (!inBlock && i+1 < line.length() && chars[i] == '/' && chars[i+1] == '*') {
                    inBlock = true;
                    i++;
                } else if (inBlock && i+1 < line.length() && chars[i] == '*' && chars[i+1] == '/') {
                    inBlock = false;
                    i++;
                } else if (!inBlock && i+1 < line.length() && chars[i] == '-' && chars[i+1] == '-') {
                    break;
				} else if (!inBlock && i+1 < line.length() && chars[i]==' ' && chars[i+1] == '-') {
                    i++ ;					
                } else if (!inBlock) {
                    newline.append(chars[i]);
                }
                i++;
            }
		if (!inBlock && newline.length() > 0) {
                ans.add(new String(newline));
            }
        }
        return ans;			
}


dialect "mvel"

rule "Generated SQL should not contain Select * "
	salience 997
	when
		 genSQL : GeneratedSQL(  StripOracleComments(genSQL.outputSQL)  contains  " Select * " )
	then
		String errorMessage = "The generated SQL contains Wild Select Statement 'Select *'";
		insert(new Response(ResponseType.FAIL, errorMessage, drools.getRule().getName()));
	end
   